main: com.wfector.notifier.ChestShopNotifier
name: ${project.name}
version: '${minecraft.plugin.version}'
description: ${project.description}
author: BetaBlaze
authors: [Phoenix616]
depend: [ChestShop]
commands:
   csn:
      description: Main ChestShopNotifier command.
      usage: /csn help|history|clear
      permission: csn.user
      permission-message: No permission
permissions:
    csn.*:
        description: Gives access to all ChestShop Notifier commands
        children:
            csn.user: true
            csn.admin: true
            csn.history.others: true
    csn.user:
        description: Basic commands for any user
        default: true
    csn.admin:
        description: Access to high-end commands
        default: op
    csn.history.others:
        description: Allow lookups on other users
        default: op