main: com.wfector.notifier.ChestShopNotifier
name: ${project.name}
version: '${minecraft.plugin.version}'
description: ${project.description}
author: BetaBlaze
authors: [Phoenix616, FrankHeijden]
depend: [ChestShop]
api-version: '1.13'
commands:
   csn:
      description: Main ChestShopNotifier command.
      usage: /csn help|history|read|clear
      permission: csn.command
      permission-message: No permission
permissions:
    csn.*:
        description: Gives access to all ChestShop Notifier commands
        children:
            csn.user: true
            csn.admin: true
    csn.user:
        description: Basic commands for any user
        children:
            csn.command: true
            csn.comamnd.history: true
            csn.command.clear: true
    csn.admin:
        description: Access to high-end commands
        children:
            csn.command.reload: true
            csn.command.upload: true
            csn.command.convert: true
            csn.command.cleandatabase: true
            csn.command.history.others: true
    csn.command:
        description: Allow access to the plugin command
        default: true
    csn.command.history:
        description: Allow history lookup
        default: true
    csn.command.clear:
        description: Allows to clear entries from the database
        default: true
    csn.command.reload:
        description: Allows reloading the plugin
        default: op
    csn.command.upload:
        description: Allows uploading the current batch
        default: op
    csn.command.convert:
        description: Allows converting of old entries
        default: op
    csn.command.cleandatabase:
        description: Allows cleaning of the database
        default: op
    csn.command.history.others:
        description: Allow lookups on other users
        default: op
    csn.history.others:
        description: Allow lookups on other users
        children:
            csn.command.history.others: true
