# Chest Shop Notifier
# Config file for 1.1.0
# August 5 2014

logging:
  admin-shop: true

notifications:
  notify-on-user-join: true
  delay-seconds: 5

debugging:
  verbose: true

database:
  host: 'localhost'
  port: 3306
  dbname: 'database1'
  username: 'dbadmin'
  password: '123456'
  
messages:
  sales: "&c ** You made &f{sales} sales&c since you last checked."
  history-cmd: "&c ** To see them, type &f/csn history&c."
  history-caption: "&dChestShop Notifier // &7Latest Commissions"
  history-empty: "&cNothing to show."
  history-bought: "&9{player} &7bought &a{count}x&9{item} &f{timeago} ago &a(+{money})"
  history-sold: "&9{player} &7sold you &c{count}x&9{item} &f{timeago} ago &c(-{money})"
  history-read: "&c- To mark these as read, type /csn clear"
  history-clear: "&cHistory cleared! New sales will continue to be recorded."