# Chest Shop Notifier
# Config file for 1.1.0
# August 5 2014

logging:
  admin-shop: true

notifications:
  notify-on-user-join: true
  delay-seconds: 5

debugging:
  verbose: true

database:
  host: 'localhost'
  port: 3306
  dbname: 'database1'
  username: 'dbadmin'
  password: '123456'